Repository bungmakase/bungmakase_frontend, pull requests merged in 2025-02, with the labels that each got.

#8 feat: 붕도감 UI 개발
  public/images/logo-empty.png
  src/app/(home)/page.tsx
  src/app/page.tsx
  src/components/common/Logo/index.tsx
Labels: feature

#9 feat: 프로필 메인페이지 UI
  public/images/svg/photo.svg
  src/app/mypage/page.tsx
Labels: feature

#16 refactor: 네비게이션 mvp 아닌것제외
  src/lib/data/navigation.ts
Labels: refactor

#18 test: 로고 옵션값추가
  src/components/common/Logo/Logo.stories.tsx
Labels: test

#17 test: 버튼
  src/components/ui/button.stories.tsx
Labels: test

#39 feature: add local https connect
  package.json
  server.js
Labels: feature

#44 feat: 붕도감
  package.json
  pnpm-lock.yaml
  src/api/home.ts
  src/app/(home)/page.tsx
  src/hooks/useToggle.ts
  src/types/home.ts
Labels: feature

#45 feat: 마이페이지
  src/api/mypage.ts
  src/app/mypage/[id]/page.tsx
  src/app/mypage/page.tsx
  src/types/mypage.ts
Labels: feature

#48 fix: 빌드 에러 수정
  src/components/common/KakaoMap.tsx
  src/components/review/SearchSection.tsx
  src/components/shop/KakaoDynamicMap.tsx
Labels: bug
